{
    "offscheduledata": [
        "Special schedule january 2025": [
            {
            "id": 31,
            "name_schedule_month": "Special schedule january 2025",
            "schedule_collection": "[\"13\", \"15\", \"17\", \"19\", \"21\", \"23\", \"25\", \"27\"]",
            "schedule_status": 0,
            "schedule_special": 1,
            "schedule_create": 1,
            "schedule_recognize": null,
            "schedule_agreed": null,
            "schedule_planner": null,
            "id_schedule_year": 1,
            "created_at": "2025-01-21 09:23:50",
            "updated_at": "2025-01-21 10:07:00",
            "schedule_start": "2025-06-02 00:00:00",
            "schedule_end": "2025-06-08 00:00:00",
            "preventive_cycle": 6,
            "schedule_date": "2025-01-19 00:00:00",
            "reschedule_date_1": null,
            "reschedule_date_2": null,
            "reschedule_date_3": null,
            "reschedule_note": null,
            "schedule_record": null,
            "machine_schedule_status": 0,
            "schedule_time_status": null,
            "machine_id": 31,
            "yearly_id": 1,
            "monthly_id": null,
            "special_id": 10,
            "invent_number": "E-JA-11-0063",
            "machine_number": "KONTRUKSI ",
            "machine_name": "WELDING CO2 MANUAL",
            "machine_brand": "O T C",
            "machine_type": "CPXDS-350",
            "machine_spec": "350 A",
            "machine_power": "18 KW",
            "machine_made": "JAPAN",
            "machine_status": 1,
            "machine_info": "KONTRUKSI ",
            "mfg_number": "P25000YA0162025",
            "install_date": "2011",
            "production_date": "2008",
            "machine_abnormal_status": 0,
            "machine_problem": null,
            "machine_action": "0",
            "property_id": null,
            "standart_id": 4,
            "schedule_id": 13
            },
            {
            "id": 32,
            "name_schedule_month": "Special schedule january 2025",
            "schedule_collection": "[\"13\", \"15\", \"17\", \"19\", \"21\", \"23\", \"25\", \"27\"]",
            "schedule_status": 0,
            "schedule_special": 1,
            "schedule_create": 1,
            "schedule_recognize": null,
            "schedule_agreed": null,
            "schedule_planner": null,
            "id_schedule_year": 1,
            "created_at": "2025-01-21 09:23:50",
            "updated_at": "2025-01-21 10:07:00",
            "schedule_start": "2025-06-09 00:00:00",
            "schedule_end": "2025-06-15 00:00:00",
            "preventive_cycle": 6,
            "schedule_date": "2025-01-06 00:00:00",
            "reschedule_date_1": "2025-01-26 00:00:00",
            "reschedule_date_2": null,
            "reschedule_date_3": null,
            "reschedule_note": "reshedule",
            "schedule_record": null,
            "machine_schedule_status": 0,
            "schedule_time_status": null,
            "machine_id": 32,
            "yearly_id": 1,
            "monthly_id": null,
            "special_id": 10,
            "invent_number": "E-JA-24-0065",
            "machine_number": "MOBIL GOLF",
            "machine_name": "WELDING CO2 MANUAL",
            "machine_brand": "O T C",
            "machine_type": "CPXDS-350",
            "machine_spec": "350 A",
            "machine_power": "18 KW",
            "machine_made": "JAPAN",
            "machine_status": 1,
            "machine_info": "PRODUKSI",
            "mfg_number": "CO311MP11449004",
            "install_date": "45605",
            "production_date": "2024",
            "machine_abnormal_status": 0,
            "machine_problem": null,
            "machine_action": "0",
            "property_id": null,
            "standart_id": 4,
            "schedule_id": 15
            },
            {
            "id": 33,
            "name_schedule_month": "Special schedule january 2025",
            "schedule_collection": "[\"13\", \"15\", \"17\", \"19\", \"21\", \"23\", \"25\", \"27\"]",
            "schedule_status": 0,
            "schedule_special": 1,
            "schedule_create": 1,
            "schedule_recognize": null,
            "schedule_agreed": null,
            "schedule_planner": null,
            "id_schedule_year": 1,
            "created_at": "2025-01-21 09:23:50",
            "updated_at": "2025-01-21 10:07:00",
            "schedule_start": "2025-06-16 00:00:00",
            "schedule_end": "2025-06-22 00:00:00",
            "preventive_cycle": 6,
            "schedule_date": "2025-01-22 00:00:00",
            "reschedule_date_1": "2025-01-21 00:00:00",
            "reschedule_date_2": null,
            "reschedule_date_3": null,
            "reschedule_note": "reshedule",
            "schedule_record": null,
            "machine_schedule_status": 0,
            "schedule_time_status": null,
            "machine_id": 33,
            "yearly_id": 1,
            "monthly_id": null,
            "special_id": 10,
            "invent_number": "E-JA-24-0066",
            "machine_number": "MOBIL GOLF",
            "machine_name": "WELDING CO2 MANUAL",
            "machine_brand": "O T C",
            "machine_type": "CPXDS-350",
            "machine_spec": "350 A",
            "machine_power": "18 KW",
            "machine_made": "JAPAN",
            "machine_status": 1,
            "machine_info": "PRODUKSI",
            "mfg_number": "CO311MP11449036",
            "install_date": "45605",
            "production_date": "2024",
            "machine_abnormal_status": 0,
            "machine_problem": null,
            "machine_action": "0",
            "property_id": null,
            "standart_id": 4,
            "schedule_id": 17
            },
            {
            "id": 34,
            "name_schedule_month": "Special schedule january 2025",
            "schedule_collection": "[\"13\", \"15\", \"17\", \"19\", \"21\", \"23\", \"25\", \"27\"]",
            "schedule_status": 0,
            "schedule_special": 1,
            "schedule_create": 1,
            "schedule_recognize": null,
            "schedule_agreed": null,
            "schedule_planner": null,
            "id_schedule_year": 1,
            "created_at": "2025-01-21 09:23:50",
            "updated_at": "2025-01-21 10:07:00",
            "schedule_start": "2025-06-23 00:00:00",
            "schedule_end": "2025-06-29 00:00:00",
            "preventive_cycle": 6,
            "schedule_date": "2025-01-21 00:00:00",
            "reschedule_date_1": "2025-01-05 00:00:00",
            "reschedule_date_2": null,
            "reschedule_date_3": null,
            "reschedule_note": "reshedule",
            "schedule_record": null,
            "machine_schedule_status": 0,
            "schedule_time_status": null,
            "machine_id": 34,
            "yearly_id": 1,
            "monthly_id": null,
            "special_id": 10,
            "invent_number": "E-JA-24-0067",
            "machine_number": "MOBIL GOLF",
            "machine_name": "WELDING CO2 MANUAL",
            "machine_brand": "O T C",
            "machine_type": "CPXDS-350",
            "machine_spec": "350 A",
            "machine_power": "18 KW",
            "machine_made": "JAPAN",
            "machine_status": 1,
            "machine_info": "PRODUKSI",
            "mfg_number": "CO311MP11449003",
            "install_date": "45605",
            "production_date": "2024",
            "machine_abnormal_status": 0,
            "machine_problem": null,
            "machine_action": "0",
            "property_id": null,
            "standart_id": 4,
            "schedule_id": 19
            },
            {
            "id": 35,
            "name_schedule_month": "Special schedule january 2025",
            "schedule_collection": "[\"13\", \"15\", \"17\", \"19\", \"21\", \"23\", \"25\", \"27\"]",
            "schedule_status": 0,
            "schedule_special": 1,
            "schedule_create": 1,
            "schedule_recognize": null,
            "schedule_agreed": null,
            "schedule_planner": null,
            "id_schedule_year": 1,
            "created_at": "2025-01-21 09:23:50",
            "updated_at": "2025-01-21 10:07:00",
            "schedule_start": "2025-06-02 00:00:00",
            "schedule_end": "2025-06-08 00:00:00",
            "preventive_cycle": 6,
            "schedule_date": "2025-01-30 00:00:00",
            "reschedule_date_1": null,
            "reschedule_date_2": null,
            "reschedule_date_3": null,
            "reschedule_note": null,
            "schedule_record": null,
            "machine_schedule_status": 0,
            "schedule_time_status": null,
            "machine_id": 35,
            "yearly_id": 1,
            "monthly_id": null,
            "special_id": 10,
            "invent_number": "E-JA-24-0068",
            "machine_number": "MOBIL GOLF",
            "machine_name": "WELDING CO2 MANUAL",
            "machine_brand": "O T C",
            "machine_type": "CPXDS-350",
            "machine_spec": "350 A",
            "machine_power": "18 KW",
            "machine_made": "JAPAN",
            "machine_status": 1,
            "machine_info": "PRODUKSI",
            "mfg_number": "CO311MP11449002",
            "install_date": "45605",
            "production_date": "2024",
            "machine_abnormal_status": 0,
            "machine_problem": null,
            "machine_action": "0",
            "property_id": null,
            "standart_id": 4,
            "schedule_id": 21
            },
            {
            "id": 36,
            "name_schedule_month": "Special schedule january 2025",
            "schedule_collection": "[\"13\", \"15\", \"17\", \"19\", \"21\", \"23\", \"25\", \"27\"]",
            "schedule_status": 0,
            "schedule_special": 1,
            "schedule_create": 1,
            "schedule_recognize": null,
            "schedule_agreed": null,
            "schedule_planner": null,
            "id_schedule_year": 1,
            "created_at": "2025-01-21 09:23:50",
            "updated_at": "2025-01-21 10:07:00",
            "schedule_start": "2025-06-09 00:00:00",
            "schedule_end": "2025-06-15 00:00:00",
            "preventive_cycle": 6,
            "schedule_date": "2025-01-16 00:00:00",
            "reschedule_date_1": "2025-01-27 00:00:00",
            "reschedule_date_2": null,
            "reschedule_date_3": null,
            "reschedule_note": "reshedule",
            "schedule_record": null,
            "machine_schedule_status": 0,
            "schedule_time_status": null,
            "machine_id": 36,
            "yearly_id": 1,
            "monthly_id": null,
            "special_id": 10,
            "invent_number": "E-JA-24-0069",
            "machine_number": "MOBIL GOLF",
            "machine_name": "WELDING CO2 MANUAL",
            "machine_brand": "O T C",
            "machine_type": "CPXDS-350",
            "machine_spec": "350 A",
            "machine_power": "18 KW",
            "machine_made": "JAPAN",
            "machine_status": 1,
            "machine_info": "PRODUKSI",
            "mfg_number": "CO311MP11449001",
            "install_date": "45605",
            "production_date": "2024",
            "machine_abnormal_status": 0,
            "machine_problem": null,
            "machine_action": "0",
            "property_id": null,
            "standart_id": 4,
            "schedule_id": 23
            },
            {
            "id": 37,
            "name_schedule_month": "Special schedule january 2025",
            "schedule_collection": "[\"13\", \"15\", \"17\", \"19\", \"21\", \"23\", \"25\", \"27\"]",
            "schedule_status": 0,
            "schedule_special": 1,
            "schedule_create": 1,
            "schedule_recognize": null,
            "schedule_agreed": null,
            "schedule_planner": null,
            "id_schedule_year": 1,
            "created_at": "2025-01-21 09:23:50",
            "updated_at": "2025-01-21 10:07:00",
            "schedule_start": "2025-06-16 00:00:00",
            "schedule_end": "2025-06-22 00:00:00",
            "preventive_cycle": 6,
            "schedule_date": "2025-01-13 00:00:00",
            "reschedule_date_1": "2025-01-20 00:00:00",
            "reschedule_date_2": null,
            "reschedule_date_3": null,
            "reschedule_note": "reshedule",
            "schedule_record": null,
            "machine_schedule_status": 0,
            "schedule_time_status": null,
            "machine_id": 37,
            "yearly_id": 1,
            "monthly_id": null,
            "special_id": 10,
            "invent_number": "E-JA-24-0070",
            "machine_number": "MOBIL GOLF",
            "machine_name": "WELDING CO2 MANUAL",
            "machine_brand": "O T C",
            "machine_type": "CPXDS-350",
            "machine_spec": "350 A",
            "machine_power": "18 KW",
            "machine_made": "JAPAN",
            "machine_status": 1,
            "machine_info": "PRODUKSI",
            "mfg_number": "CO311MP11449037",
            "install_date": "45605",
            "production_date": "2024",
            "machine_abnormal_status": 0,
            "machine_problem": null,
            "machine_action": "0",
            "property_id": null,
            "standart_id": 4,
            "schedule_id": 25
            },
            {
            "id": 38,
            "name_schedule_month": "Special schedule january 2025",
            "schedule_collection": "[\"13\", \"15\", \"17\", \"19\", \"21\", \"23\", \"25\", \"27\"]",
            "schedule_status": 0,
            "schedule_special": 1,
            "schedule_create": 1,
            "schedule_recognize": null,
            "schedule_agreed": null,
            "schedule_planner": null,
            "id_schedule_year": 1,
            "created_at": "2025-01-21 09:23:50",
            "updated_at": "2025-01-21 10:07:00",
            "schedule_start": "2025-06-23 00:00:00",
            "schedule_end": "2025-06-29 00:00:00",
            "preventive_cycle": 6,
            "schedule_date": "2025-01-19 00:00:00",
            "reschedule_date_1": null,
            "reschedule_date_2": null,
            "reschedule_date_3": null,
            "reschedule_note": null,
            "schedule_record": null,
            "machine_schedule_status": 0,
            "schedule_time_status": null,
            "machine_id": 38,
            "yearly_id": 1,
            "monthly_id": null,
            "special_id": 10,
            "invent_number": "E-JA-24-0071",
            "machine_number": "MOBIL GOLF",
            "machine_name": "WELDING CO2 MANUAL",
            "machine_brand": "O T C",
            "machine_type": "CPXDS-350",
            "machine_spec": "350 A",
            "machine_power": "18 KW",
            "machine_made": "JAPAN",
            "machine_status": 1,
            "machine_info": "PRODUKSI",
            "mfg_number": "CO311MP11449005",
            "install_date": "45605",
            "production_date": "2024",
            "machine_abnormal_status": 0,
            "machine_problem": null,
            "machine_action": "0",
            "property_id": null,
            "standart_id": 4,
            "schedule_id": 27
            },
        ],
        "Special schedule february 2025"; [
            {
            "id": 144,
            "name_schedule_month": "Special schedule february 2025",
            "schedule_collection": "[\"48\", \"56\"]",
            "schedule_status": 0,
            "schedule_special": 1,
            "schedule_create": 1,
            "schedule_recognize": null,
            "schedule_agreed": null,
            "schedule_planner": null,
            "id_schedule_year": 1,
            "created_at": "2025-01-21 09:23:51",
            "updated_at": "2025-01-21 10:07:47",
            "schedule_start": "2025-10-14 00:00:00",
            "schedule_end": "2025-10-20 00:00:00",
            "preventive_cycle": 6,
            "schedule_date": "2025-01-12 00:00:00",
            "reschedule_date_1": null,
            "reschedule_date_2": null,
            "reschedule_date_3": null,
            "reschedule_note": null,
            "schedule_record": null,
            "machine_schedule_status": 0,
            "schedule_time_status": null,
            "machine_id": 144,
            "yearly_id": 1,
            "monthly_id": null,
            "special_id": 11,
            "invent_number": "E-KB-05-0001",
            "machine_number": "M1",
            "machine_name": "DRILLING MACHINE",
            "machine_brand": "HORNG DAR",
            "machine_type": "HD - 25",
            "machine_spec": "25 MM",
            "machine_power": "1,5 KW",
            "machine_made": "TAIWAN",
            "machine_status": 1,
            "machine_info": "PRODUKSI",
            "mfg_number": "9309",
            "install_date": "2005",
            "production_date": "2005",
            "machine_abnormal_status": 0,
            "machine_problem": null,
            "machine_action": "0",
            "property_id": null,
            "standart_id": 5,
            "schedule_id": 48
            },
            {
            "id": 148,
            "name_schedule_month": "Special schedule february 2025",
            "schedule_collection": "[\"48\", \"56\"]",
            "schedule_status": 0,
            "schedule_special": 1,
            "schedule_create": 1,
            "schedule_recognize": null,
            "schedule_agreed": null,
            "schedule_planner": null,
            "id_schedule_year": 1,
            "created_at": "2025-01-21 09:23:51",
            "updated_at": "2025-01-21 10:07:47",
            "schedule_start": "2025-10-14 00:00:00",
            "schedule_end": "2025-10-20 00:00:00",
            "preventive_cycle": 6,
            "schedule_date": "2025-01-24 00:00:00",
            "reschedule_date_1": null,
            "reschedule_date_2": null,
            "reschedule_date_3": null,
            "reschedule_note": null,
            "schedule_record": null,
            "machine_schedule_status": 0,
            "schedule_time_status": null,
            "machine_id": 148,
            "yearly_id": 1,
            "monthly_id": null,
            "special_id": 11,
            "invent_number": "E-KB-17-0008",
            "machine_number": "M5",
            "machine_name": "DRILLING MACHINE ",
            "machine_brand": "MORITA",
            "machine_type": "RF-32",
            "machine_spec": null,
            "machine_power": null,
            "machine_made": null,
            "machine_status": 1,
            "machine_info": "PRODUKSI",
            "mfg_number": "1060451",
            "install_date": null,
            "production_date": "2017",
            "machine_abnormal_status": 0,
            "machine_problem": null,
            "machine_action": "0",
            "property_id": null,
            "standart_id": 5,
            "schedule_id": 56
            }
        ]
  ]
}
